from __future__ import annotations
import argparse, math, os
from pathlib import Path
from collections import defaultdict
from pathlib import Path
from pymol import cmd, util
from hdxms.colors import CHIMERAX_HEX, PYMOL_RGB, bin_name
from hdxms.io import load_hdx_csv, apply_offsets


def _ranges(values):
    values = sorted(set(values))
    if not values: return []
    out=[]; start=end=values[0]
    for value in values[1:]:
        if value == end + 1: end=value
        else: out.append(f"{start}-{end}" if start != end else str(start)); start=end=value
    out.append(f"{start}-{end}" if start != end else str(start))
    return out



# HDXMS_CHIMERAX_EXPORT

CHIMERAX_HEX = {
    "hdx_blue3": "#3366E6",
    "hdx_blue2": "#6699FF",
    "hdx_blue1": "#A6BFFF",
    "hdx_gray0": "#595959",
    "hdx_red1": "#FFB3B3",
    "hdx_red2": "#F27373",
    "hdx_red3": "#D93333",
    "hdx_unmapped": "#BFBFBF",
}


def _compress_chimerax_ranges(residues):
    residues = sorted(set(int(r) for r in residues))

    if not residues:
        return []

    output = []
    start = previous = residues[0]

    for residue in residues[1:]:
        if residue == previous + 1:
            previous = residue
            continue

        output.append(
            f"{start}-{previous}" if start != previous else str(start)
        )
        start = previous = residue

    output.append(
        f"{start}-{previous}" if start != previous else str(start)
    )

    return output


def write_chimerax_script(output_path, structure_path, mapped):
    """
    Write a ChimeraX .cxc script using the exact PyMOL HDX bins
    and RGB colors.
    """
    output_path = Path(output_path).expanduser().resolve()
    structure_path = Path(structure_path).expanduser().resolve()

    grouped = defaultdict(lambda: defaultdict(list))

    for (chain, residue), value in mapped.items():
        value = float(value)

        if not chain or not math.isfinite(value):
            continue

        color_name = bin_name(value)

        if color_name is not None:
            grouped[color_name][str(chain)].append(int(residue))

    lines = [
        "# ChimeraX HDX coloring script",
        "# Generated by hdxms color",
        "# Uses the same discrete bins and RGB colors as PyMOL.",
        "",
        f'open "{structure_path}"',
        "",
        "# Hide all default representations",
        "hide",
        "",
        "# Protein cartoon",
        "show protein cartoons",
        f"color protein {CHIMERAX_HEX['hdx_unmapped']} target c",
        "",
        "# DNA",
        "show nucleic atoms",
        "style nucleic stick",
        "color nucleic byelement",
        "",
        "# NAD and other non-polymer organic ligands",
        "show ligand atoms",
        "style ligand stick",
        "color ligand byelement",
        "",
        "# HDX coloring",
    ]

    color_order = (
        "hdx_blue3",
        "hdx_blue2",
        "hdx_blue1",
        "hdx_gray0",
        "hdx_red1",
        "hdx_red2",
        "hdx_red3",
    )

    for color_name in color_order:
        for chain, residues in sorted(grouped[color_name].items()):
            for residue_range in _compress_chimerax_ranges(residues):
                lines.append(
                    f"color /{chain}:{residue_range} "
                    f"{CHIMERAX_HEX[color_name]} target c"
                )

    lines.extend(
        [
            "",
            "set bgColor white",
            "lighting soft",
            "view protein",
            "",
        ]
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines) + "\n")

    print(f"Wrote ChimeraX script: {output_path}")

def _write_chimerax_script(output_path, structure_path, grouped):
    output = Path(output_path).expanduser().resolve()
    structure = Path(structure_path).expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# MADP HDX Palette v1.0",
        f'open "{structure}"',
        "hide",
        "show protein cartoons",
        f"color protein {CHIMERAX_HEX['hdx_unmapped']} target c",
        "show nucleic atoms",
        "style nucleic stick",
        "color nucleic byelement",
        "show ligand atoms",
        "style ligand stick",
        "color ligand byelement",
    ]
    for color_name in (
        "hdx_blue3", "hdx_blue2", "hdx_blue1", "hdx_gray0",
        "hdx_red1", "hdx_red2", "hdx_red3",
    ):
        for chain, residues in sorted(grouped.get(color_name, {}).items()):
            chain_prefix = f"/{chain}" if chain else ""
            for residue_range in _ranges(residues):
                lines.append(
                    f"color {chain_prefix}:{residue_range} "
                    f"{CHIMERAX_HEX[color_name]} target c"
                )
    lines.extend(["set bgColor white", "lighting soft", "view protein"])
    output.write_text("\n".join(lines) + "\n")


def run(args):
    obj = os.path.splitext(os.path.basename(args.structure))[0]
    cmd.load(args.structure, obj)
    for name, rgb in PYMOL_RGB.items(): cmd.set_color(name, rgb)
    df = apply_offsets(load_hdx_csv(args.csv, args.value_col), args.offset, args.offset_per_chain)
    if args.chain_filter:
        allowed=set(args.chain_filter.split(',')); df=df[(df.chain=='') | df.chain.isin(allowed)]
    sums=defaultdict(float); counts=defaultdict(int)
    for row in df.itertuples(index=False):
        value = float(row.value)
        if not math.isfinite(value):
            continue
        for residue in range(row.start, row.end + 1):
            sums[(row.chain, residue)] += value
            counts[(row.chain, residue)] += 1
    model=cmd.get_model(f"{obj} and polymer.protein")
    present=defaultdict(set)
    for atom in model.atom:
        try: present[atom.chain].add(int(atom.resi))
        except ValueError: pass
    mapped={}
    for chain,residues in present.items():
        if args.chain_filter and chain not in set(args.chain_filter.split(',')): continue
        for residue in residues:
            key=(chain,residue) if (chain,residue) in sums else ('',residue)
            if counts.get(key,0) >= args.mincov: mapped[(chain,residue)] = sums[key]/counts[key]
    cmd.hide('everything','all'); cmd.show('cartoon',f'{obj} and polymer.protein')
    cmd.color('hdx_unmapped',f'{obj} and polymer.protein')
    grouped=defaultdict(lambda: defaultdict(list))
    for (chain,residue),value in mapped.items(): grouped[bin_name(value)][chain].append(residue)
    for color,chain_map in grouped.items():
        if color is None: continue
        for chain,residues in chain_map.items():
            cmd.color(color, f"{obj} and chain {chain} and polymer.protein and resi {'+'.join(_ranges(residues))}")
    if not args.protein_only:
        cmd.show('sticks',f'{obj} and polymer.nucleic'); util.cbaw(f'{obj} and polymer.nucleic')
        cmd.show('sticks',f'{obj} and organic'); util.cbag(f'{obj} and organic')
    cmd.set('cartoon_transparency',args.cartoon_trans); cmd.bg_color('white'); cmd.orient(f'{obj} and polymer.protein')
    if args.out_bfactor_pdb:
        cmd.alter(f'{obj} and polymer.protein','b=0.0')
        for (chain,residue),value in mapped.items(): cmd.alter(f'{obj} and chain {chain} and resi {residue}',f'b={float(value)}')
        cmd.save(args.out_bfactor_pdb,obj)
    # HDXMS_WRITE_CHIMERAX
    out_chimerax = getattr(args, "out_chimerax", None)
    if out_chimerax:
        chimerax_structure = (
            args.out_bfactor_pdb
            if args.out_bfactor_pdb
            else args.structure
        )
        write_chimerax_script(
            out_chimerax,
            chimerax_structure,
            mapped,
        )

    out_chimerax = getattr(args, 'out_chimerax', None)
    if out_chimerax:
        structure_for_chimerax = args.out_bfactor_pdb or args.structure
        _write_chimerax_script(out_chimerax, structure_for_chimerax, grouped)
    if args.session: cmd.save(args.session)
    if args.out_png:
        cmd.viewport(args.width,args.height); cmd.ray(); cmd.png(args.out_png,dpi=args.dpi)


def main(argv=None):
    parser=argparse.ArgumentParser()
    parser.add_argument('structure'); parser.add_argument('csv')
    parser.add_argument('--value-col',default='pctD_diff'); parser.add_argument('--chain-filter')
    parser.add_argument('--offset',type=int,default=0); parser.add_argument('--offset-per-chain')
    parser.add_argument('--mincov',type=int,default=1); parser.add_argument('--cartoon-trans',type=float,default=0.0)
    parser.add_argument('--protein-only',action='store_true'); parser.add_argument('--out-png'); parser.add_argument('--session')
    parser.add_argument('--out-bfactor-pdb'); parser.add_argument('--out-chimerax'); parser.add_argument('--width',type=int,default=1800); parser.add_argument('--height',type=int,default=1400)
    parser.add_argument('--dpi',type=int,default=300)
    run(parser.parse_args(argv))


if __name__ == "__main__":
    main()
