from __future__ import annotations

import argparse
import math
import os
from collections import defaultdict
from pathlib import Path

from pymol import cmd, util

from hdxms.colors import CHIMERAX_HEX, PYMOL_RGB, bin_name
from hdxms.io import apply_offsets, load_hdx_csv


def _ranges(values):
    """Collapse residue numbers into compact contiguous ranges."""
    values = sorted(set(int(value) for value in values))
    if not values:
        return []

    output = []
    start = end = values[0]

    for value in values[1:]:
        if value == end + 1:
            end = value
        else:
            output.append(f"{start}-{end}" if start != end else str(start))
            start = end = value

    output.append(f"{start}-{end}" if start != end else str(start))
    return output


def _selection(obj: str, chain: str, residues) -> str:
    residue_expression = "+".join(_ranges(residues))
    chain_clause = f" and chain {chain}" if chain else ""
    return (
        f"{obj}{chain_clause} and polymer.protein "
        f"and resi {residue_expression}"
    )


def _write_chimerax_script(
    output_path: str,
    structure_path: str,
    grouped,
) -> None:
    """Write a ChimeraX script using the exact canonical discrete palette."""
    output = Path(output_path).expanduser().resolve()
    structure = Path(structure_path).expanduser().resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# MADP HDX Palette v1.0",
        "# Generated by hdxms color",
        f'open "{structure}"',
        "hide",
        "show protein cartoons",
        f"color protein {CHIMERAX_HEX['hdx_unmapped']} target c",
        "show nucleic atoms",
        "style nucleic stick",
        "color nucleic byelement",
        "show ligand atoms",
        "style ligand stick",
        "color ligand byelement",
        "",
        "# Discrete HDX residue colors",
    ]

    color_order = (
        "hdx_blue3",
        "hdx_blue2",
        "hdx_blue1",
        "hdx_gray0",
        "hdx_red1",
        "hdx_red2",
        "hdx_red3",
    )

    for color_name in color_order:
        for chain, residues in sorted(grouped.get(color_name, {}).items()):
            chain_prefix = f"/{chain}" if chain else ""
            for residue_range in _ranges(residues):
                lines.append(
                    f"color {chain_prefix}:{residue_range} "
                    f"{CHIMERAX_HEX[color_name]} target c"
                )

    lines.extend(
        [
            "",
            "set bgColor white",
            "lighting soft",
            "view protein",
        ]
    )

    output.write_text("\n".join(lines) + "\n")
    print(f"Wrote ChimeraX script: {output}")


def run(args):
    obj = os.path.splitext(os.path.basename(args.structure))[0]
    cmd.load(args.structure, obj)

    for name, rgb in PYMOL_RGB.items():
        cmd.set_color(name, rgb)

    df = apply_offsets(
        load_hdx_csv(args.csv, args.value_col),
        args.offset,
        args.offset_per_chain,
    )

    allowed = None
    if args.chain_filter:
        allowed = {
            chain.strip()
            for chain in args.chain_filter.split(",")
            if chain.strip()
        }
        df = df[(df.chain == "") | df.chain.isin(allowed)]

    sums = defaultdict(float)
    counts = defaultdict(int)

    for row in df.itertuples(index=False):
        value = float(row.value)
        if not math.isfinite(value):
            continue

        for residue in range(int(row.start), int(row.end) + 1):
            key = (row.chain, residue)
            sums[key] += value
            counts[key] += 1

    model = cmd.get_model(f"{obj} and polymer.protein")
    present = defaultdict(set)

    for atom in model.atom:
        try:
            present[atom.chain].add(int(atom.resi))
        except ValueError:
            continue

    mapped = {}
    for chain, residues in present.items():
        if allowed is not None and chain not in allowed:
            continue

        for residue in residues:
            chain_key = (chain, residue)
            blank_key = ("", residue)
            key = chain_key if chain_key in sums else blank_key

            if counts.get(key, 0) >= args.mincov:
                mapped[(chain, residue)] = sums[key] / counts[key]

    cmd.hide("everything", "all")
    cmd.show("cartoon", f"{obj} and polymer.protein")
    cmd.color("hdx_unmapped", f"{obj} and polymer.protein")

    grouped = defaultdict(lambda: defaultdict(list))
    for (chain, residue), value in mapped.items():
        color_name = bin_name(value)
        if color_name is not None:
            grouped[color_name][chain].append(residue)

    for color_name, chain_map in grouped.items():
        for chain, residues in chain_map.items():
            cmd.color(color_name, _selection(obj, chain, residues))

    if not args.protein_only:
        cmd.show("sticks", f"{obj} and polymer.nucleic")
        util.cbaw(f"{obj} and polymer.nucleic")
        cmd.show("sticks", f"{obj} and organic")
        util.cbag(f"{obj} and organic")

    cmd.set("cartoon_transparency", args.cartoon_trans)
    cmd.bg_color("white")
    cmd.orient(f"{obj} and polymer.protein")

    if args.out_bfactor_pdb:
        # Preserve original B factors for unmapped atoms and update only residues
        # that carry finite HDX values.
        for (chain, residue), value in mapped.items():
            chain_clause = f" and chain {chain}" if chain else ""
            cmd.alter(
                f"{obj}{chain_clause} and polymer.protein and resi {residue}",
                f"b={float(value)}",
            )
        cmd.save(args.out_bfactor_pdb, obj)

    if args.out_chimerax:
        chimerax_structure = args.out_bfactor_pdb or args.structure
        _write_chimerax_script(
            args.out_chimerax,
            chimerax_structure,
            grouped,
        )

    if args.session:
        cmd.save(args.session)

    if args.out_png:
        cmd.viewport(args.width, args.height)
        cmd.ray()
        cmd.png(args.out_png, dpi=args.dpi)


def main(argv=None):
    parser = argparse.ArgumentParser()
    parser.add_argument("structure")
    parser.add_argument("csv")
    parser.add_argument("--value-col", default="pctD_diff")
    parser.add_argument("--chain-filter")
    parser.add_argument("--offset", type=int, default=0)
    parser.add_argument("--offset-per-chain")
    parser.add_argument("--mincov", type=int, default=1)
    parser.add_argument("--cartoon-trans", type=float, default=0.0)
    parser.add_argument("--protein-only", action="store_true")
    parser.add_argument("--out-png")
    parser.add_argument("--session")
    parser.add_argument("--out-bfactor-pdb")
    parser.add_argument("--out-chimerax")
    parser.add_argument("--width", type=int, default=1800)
    parser.add_argument("--height", type=int, default=1400)
    parser.add_argument("--dpi", type=int, default=300)
    run(parser.parse_args(argv))


if __name__ == "__main__":
    main()
